#ifndef IMP_ARCH_DR
#define IMP_ARCH_DR

typedef enum _IA32_DEBUG_ADDRESS_REGISTERS
{
	IA32_DAR_DR0,
	IA32_DAR_DR1,
	IA32_DAR_DR2,
	IA32_DAR_DR3,
}IA32_DEBUG_ADDRESS_REGISTERS, *PIA32_DEBUG_ADDRESS_REGISTERS;

typedef struct _IA32_DEBUG_ADDRESS_REGISTER 
{
	UINT64 Address;
} IA32_DEBUG_ADDRESS_REGISTER, *PIA32_DEBUG_ADDRESS_REGISTER;

#endif