#ifndef IMP_ARCH_INTERRUPT_H
#define IMP_ARCH_INTERRUPT_H

typedef enum _X86_EXCEPTION
{
    EXCEPTION_DIVIDE_ERROR,
	EXCEPTION_DEBUG_BREAKPOINT,
	EXCEPTION_NON_MASKABLE_INTERRUPT,
	EXCEPTION_BREAKPOINT,
	EXCEPTION_OVERFLOW,
	EXCEPTION_BOUND_RANGE_EXCEEDED,
	EXCEPTION_UNDEFINED_OPCODE,
	EXCEPTION_NO_MATH_COPROCESSOR,
	EXCEPTION_DOUBLE_FAULT,
	EXCEPTION_INVALID_TSS = 10,
	EXCEPTION_SEGMENT_NOT_PRESENT,
	EXCEPTION_STACK_SEGMENT_FAULT,
	EXCEPTION_GENERAL_PROTECTION_FAULT,
	EXCEPTION_PAGE_FAULT,
	EXCEPTION_MATH_FAULT = 16,
	EXCEPTION_ALIGNMENT_CHECK,
	EXCEPTION_MACHINE_CHECK,
	EXCEPTION_SIMD_FLOATING_POINT_NUMERIC_ERROR,
	EXCEPTION_VIRTUAL_EXCEPTION
} X86_EXCEPTION, *PX86_EXCEPTION;

typedef enum _X86_INTERRUPT_TYPE
{
   	INTERRUPT_TYPE_EXTERNAL_INTERRUPT,
	INTERRUPT_TYPE_RESERVED,
	INTERRUPT_TYPE_NMI,
	INTERRUPT_TYPE_HARDWARE_EXCEPTION,
	INTERRUPT_TYPE_SOFTWARE_INTERRUPT,
	INTERRUPT_TYPE_PRIVILEGED_SOFTWARE_INTERRUPT,
	INTERRUPT_TYPE_SOFTWARE_EXCEPTION,
	INTERRUPT_TYPE_OTHER_EVENT 
} X86_INTERRUPT_TYPE, *PX86_INTERRUPT_TYPE;

#endif
